import type { SimItem } from "./seed-sim";

export type SeedItem = Omit<SimItem, "key"> & {
  name: string;
  unit: string;
  price: number;
  threshold: number;
};

// Typical Kochi kirana stock. Demand is units/day; unit is the pack an item is counted in.
export const CATALOG: Record<string, SeedItem[]> = {
  Grains: [
    {
      name: "Matta Rice 5kg",
      unit: "bag",
      price: 310,
      threshold: 8,
      demand: 3,
      openingStock: 40,
      reorderAt: 10,
      reorderQty: 30,
    },
    {
      name: "Ponni Rice 5kg",
      unit: "bag",
      price: 290,
      threshold: 6,
      demand: 1.8,
      openingStock: 25,
      reorderAt: 7,
      reorderQty: 20,
    },
    {
      name: "Wheat Atta 1kg",
      unit: "pack",
      price: 58,
      threshold: 8,
      demand: 2.5,
      openingStock: 30,
      reorderAt: 8,
      reorderQty: 25,
    },
    {
      name: "Toor Dal 1kg",
      unit: "pack",
      price: 165,
      threshold: 5,
      demand: 1.2,
      openingStock: 20,
      reorderAt: 5,
      reorderQty: 15,
    },
    {
      name: "Sugar 1kg",
      unit: "pack",
      price: 46,
      threshold: 10,
      demand: 4,
      openingStock: 50,
      reorderAt: 12,
      reorderQty: 40,
    },
    {
      name: "Rava 500g",
      unit: "pack",
      price: 32,
      threshold: 5,
      demand: 1.5,
      openingStock: 20,
      reorderAt: 5,
      reorderQty: 15,
    },
    {
      name: "Puttu Podi 1kg",
      unit: "pack",
      price: 75,
      threshold: 5,
      demand: 2,
      openingStock: 25,
      reorderAt: 6,
      reorderQty: 20,
    },
    // New item, only a week old
    {
      name: "Appam Podi 1kg",
      unit: "pack",
      price: 80,
      threshold: 4,
      demand: 1.4,
      openingStock: 12,
      reorderAt: 0,
      reorderQty: 0,
      ageDays: 6,
    },
  ],
  Oils: [
    {
      name: "Coconut Oil 1L",
      unit: "bottle",
      price: 240,
      threshold: 6,
      demand: 2.2,
      openingStock: 30,
      reorderAt: 8,
      reorderQty: 24,
    },
    {
      name: "Sunflower Oil 1L",
      unit: "pouch",
      price: 150,
      threshold: 6,
      demand: 2,
      openingStock: 25,
      reorderAt: 6,
      reorderQty: 20,
    },
    {
      name: "Palm Oil 1L",
      unit: "pouch",
      price: 110,
      threshold: 4,
      demand: 0.8,
      openingStock: 12,
      reorderAt: 3,
      reorderQty: 10,
    },
    // Slow mover
    {
      name: "Gingelly Oil 500ml",
      unit: "bottle",
      price: 190,
      threshold: 2,
      demand: 0.15,
      openingStock: 8,
      reorderAt: 1,
      reorderQty: 5,
    },
    // Running out: restocking stopped
    {
      name: "Mustard Oil 1L",
      unit: "bottle",
      price: 175,
      threshold: 3,
      demand: 0.7,
      openingStock: 15,
      reorderAt: 3,
      reorderQty: 10,
      noRestockLastDays: 20,
    },
  ],
  Snacks: [
    {
      name: "Parle-G 250g",
      unit: "pack",
      price: 25,
      threshold: 12,
      demand: 6,
      openingStock: 60,
      reorderAt: 15,
      reorderQty: 48,
    },
    {
      name: "Good Day 200g",
      unit: "pack",
      price: 40,
      threshold: 8,
      demand: 3,
      openingStock: 36,
      reorderAt: 10,
      reorderQty: 30,
    },
    {
      name: "Banana Chips 200g",
      unit: "pack",
      price: 90,
      threshold: 6,
      demand: 2.5,
      openingStock: 25,
      reorderAt: 6,
      reorderQty: 20,
      noRestockLastDays: 10,
    },
    {
      name: "Lays Classic 52g",
      unit: "pack",
      price: 20,
      threshold: 10,
      demand: 5,
      openingStock: 50,
      reorderAt: 12,
      reorderQty: 40,
    },
    {
      name: "Kerala Mixture 200g",
      unit: "pack",
      price: 60,
      threshold: 5,
      demand: 1.6,
      openingStock: 20,
      reorderAt: 5,
      reorderQty: 15,
    },
    {
      name: "Achappam 250g",
      unit: "pack",
      price: 70,
      threshold: 4,
      demand: 0.9,
      openingStock: 12,
      reorderAt: 3,
      reorderQty: 10,
    },
  ],
  Beverages: [
    {
      name: "Tea Powder 250g",
      unit: "pack",
      price: 130,
      threshold: 6,
      demand: 2.4,
      openingStock: 30,
      reorderAt: 8,
      reorderQty: 24,
    },
    {
      name: "Bru Coffee 100g",
      unit: "jar",
      price: 175,
      threshold: 4,
      demand: 1,
      openingStock: 15,
      reorderAt: 4,
      reorderQty: 12,
    },
    {
      name: "Horlicks 500g",
      unit: "jar",
      price: 285,
      threshold: 3,
      demand: 0.6,
      openingStock: 10,
      reorderAt: 3,
      reorderQty: 8,
    },
    {
      name: "Milma Milk 500ml",
      unit: "packet",
      price: 26,
      threshold: 15,
      demand: 22,
      openingStock: 40,
      reorderAt: 30,
      reorderQty: 30,
    },
    {
      name: "Coca-Cola 750ml",
      unit: "bottle",
      price: 40,
      threshold: 6,
      demand: 2.8,
      openingStock: 24,
      reorderAt: 0,
      reorderQty: 0,
      ageDays: 10,
    },
    // Almost no recent demand
    {
      name: "Boost 500g",
      unit: "jar",
      price: 270,
      threshold: 2,
      demand: 0.05,
      openingStock: 6,
      reorderAt: 0,
      reorderQty: 0,
    },
  ],
  Toiletries: [
    {
      name: "Colgate 100g",
      unit: "tube",
      price: 55,
      threshold: 5,
      demand: 1.5,
      openingStock: 30,
      reorderAt: 6,
      reorderQty: 24,
    },
    {
      name: "Lifebuoy Soap 125g",
      unit: "bar",
      price: 38,
      threshold: 8,
      demand: 2.5,
      openingStock: 36,
      reorderAt: 8,
      reorderQty: 30,
    },
    {
      name: "Medimix Soap 125g",
      unit: "bar",
      price: 45,
      threshold: 8,
      demand: 2,
      openingStock: 30,
      reorderAt: 8,
      reorderQty: 24,
    },
    {
      name: "Clinic Plus Shampoo 175ml",
      unit: "bottle",
      price: 115,
      threshold: 3,
      demand: 0.6,
      openingStock: 12,
      reorderAt: 3,
      reorderQty: 10,
    },
    {
      name: "Vim Bar 200g",
      unit: "bar",
      price: 20,
      threshold: 6,
      demand: 1.8,
      openingStock: 25,
      reorderAt: 6,
      reorderQty: 20,
    },
    {
      name: "Surf Excel 1kg",
      unit: "pack",
      price: 145,
      threshold: 4,
      demand: 1,
      openingStock: 15,
      reorderAt: 3,
      reorderQty: 12,
      noRestockLastDays: 15,
    },
  ],
};
